### ISSUE TITLE
Media does not get migrated using the v3 SQL to v4 SQL migration scripts

### ISSUE THREAD

**Issue by callumgare** [strapi/migration-scripts#112]
Media entries in the upload_file table do get copied into the new files table but are not displayed in the strapi media library ui (I'm upgrading to strapi version 4.12.4). I found this could be fixed by adding `folder_path: "/"` below line 44 in https://github.com/strapi/migration-scripts/blob/30aedca3233ae28475dba301b963b4f106c90119/v3-sql-v4-sql/migrate/migrateFiles.js

Unfortunately I don't have the capacity to write a proper PR and do testing and all that but I thought I should open an issue in case anyone else runs into this and it's helpful to them or someone wants to properly fix this.

Ta!

**Comment by derrickmehaffy** [comment]
Indeed this is related to https://docs.strapi.io/dev-docs/migration/v4/migration-guide-4.7.0-to-4.11.4 so we should add this one in by default

**Comment by derrickmehaffy** [comment]
Fixed in #116
