### ISSUE TITLE
Migration script fails on relationships

### ISSUE THREAD

**Issue by tim9009** [strapi/migration-scripts#117]
### Required System information

- Node.js version: v18.18.0
- NPM version: 9.8.1
- Source Strapi version: v3.6.5
- Target Strapi version: v4
- Source Database: postgresql
- Target Database: postgresql
- Operating system: MacOS
- Which script are you running: v3-sql-v4-sql

### Describe the bug

When running the migration script the script exits with an error every time it is about to migrate a table that includes an id, for example: `Key (page_id)=(9) is not present in table "pages".`. When looking at the rows in the pages table of the source database I can confirm that the page with id 9 does exist.

### Screenshots
![screenshot](https://github.com/strapi/migration-scripts/assets/2582197/36324f39-37dd-4d51-84b1-45454d444805)

**Comment by lukaszewczak** [comment]
@tim9009 I had the same issue, but I didn't notice the first message in the console `Error setting session_replication_role to replica, you may get foreign key constraint errors`. After running migration with users who have correct permissions migration works.

**Comment by tim9009** [comment]
Thank you for pointing that out @lukaszewczak! I ran the migration as a superuser and that allowed the scrip to finish with no errors 🎉

**Comment by derrickmehaffy** [comment]
Will close this one as solved :)
