### ISSUE TITLE
Table for localizations_links dont exist after migration

### ISSUE THREAD

**Issue by VallyPepyako** [strapi/migration-scripts#25]
### Describe the bug

Can't handle all locales from single type after migration from strapi 3 

### Steps to reproduce the behavior

Fixed manually by run something like
`insert into `blog_page_localizations_links` (`blog_id`, `inv_blog_id`) values (2, 1)
insert into `blog_page_localizations_links` (`blog_id`, `inv_blog_id`) values (1, 2)`

**Comment by derrickmehaffy** [comment]
Please completely fill out the bug report, marking this as closed. Please reopen a new bug following the complete bug report template.
