### ISSUE TITLE
Script crashes when trying to migrate columns that don't exist in v4

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/migration-scripts#26]
### Required System information

- Node.js version: v14
- NPM version: v6
- Source Strapi version:  3.6.8
- Target Strapi version: 4.2.3
- Source Database: PG
- Target Database: PG
- Operating system: Linux Mint 21
- Which script are you running: v3-sql to v4-sql

### Describe the bug

When old columns were not deleted (caused by: https://github.com/strapi/strapi/issues/1114 most likely) the script will try to transfer data from these columns but since they don't exist on v4 the script crashes. We gracefully handle this for tables but not columns.

### Steps to reproduce the behavior

1. Create a field in a content-type on v3
2. Delete the field (leaves trace of column in db due to issue 1114)
3. Try to migrate data from content-type to v4
4. See error (sanitized example below)

![image](https://user-images.githubusercontent.com/8593673/180046614-fc7d4832-63e3-45bd-bc02-148e81cc1772.png)

### Expected behavior

We should gracefully handle fields that exist in v3 database that don't in v4 and ideally warn the user that the field was missing and data was not transferred for it.

### Additional context

@martincapek If you need more info, if you are working on this, ping me on slack as I have a customer's project that I was troubleshooting and can help to show you how to reproduce this.

**Comment by derrickmehaffy** [comment]
Temporary workaround is to clean your v3 database of fields that have been deleted. It's very time consuming and annoying but is currently the only known workaround until we work on a fix.

**Comment by derrickmehaffy** [comment]
cc @marcoautiero

**Comment by GregorSondermeier** [comment]
We're trying to migrate from v3 to v4 and we're facing the same issue. We have some tables that do not exist anymore (some deleted content types) and some columns that do not exist anymore (some deleted fields within a content type that strapi v3 kept as explained in https://github.com/strapi/strapi/issues/1114).

For the missing tables we get a warning and the script continues, for the missing fields we get an error and the script aborts.

Manually cleaning the v3 database is quite cumbersome. Luckily @martincapek created a [PR](https://github.com/strapi/migration-scripts/pull/30) already.
