### ISSUE TITLE
Script crashes when trying to insert or update on table "x_components" violates foreign key constraint "x_components_entity_fk"

### ISSUE THREAD

**Issue by bananafreak** [strapi/migration-scripts#27]
### Required System information

- Node.js version: v16
- NPM version: v6
- Source Strapi version: 3.6.8
- Target Strapi version: 4.2.0
- Source Database: PG
- Target Database: PG
- Operating system: Linux POP OS 22.04
- Which script are you running: v3-sql to v4-sql

### Describe the bug

insert or update on table "x_components" violates foreign key constraint "x_entity_fk"

### Screenshots

![1](https://user-images.githubusercontent.com/18612567/180389833-be0f646f-5d44-4101-93a5-78748fbce05c.jpg)

**Comment by cruonline** [comment]
I have the same issue. Components are migrated before target entities, so we get constraint violation.

**Comment by martincapek** [comment]
@bananafreak  @marcoautiero So if I understand correctly you have relation for model in component right?

**Comment by martincapek** [comment]
Also what version of PG are you using? For import is set DB as replica so no foreign check should be done 
 
```
async function migrate() {
  if (isPGSQL) {
      await dbV4.raw("set session_replication_role to replica;");
    }
```

**Comment by cruonline** [comment]
I am using 14.4, but I disabled replica mode, as I don't have enough right to do so (Heroku PG)
My workaround was changing order of migrations, so models are done before components.
Now it works fine.

**Comment by martincapek** [comment]
Okey, thanks for info! :)

**Comment by bananafreak** [comment]
we actually used the same workaround as @cruonline

**Comment by derrickmehaffy** [comment]
> 

@cruonline / @bananafreak are either of you open to creating a pull request with your workaround please?

Thanks you

**Comment by derrickmehaffy** [comment]
It appears that for the vast majority of use-cases replica mode should work, for those that run into issues like the above it might be easier to migrate locally and export a database dump to upload remotely or use the suggestions above.

For now I'll set this issue as closed as generally this is handled by setting the DB into replica mode which we handle automatically.
