### ISSUE TITLE
v3-sql-to-v4-sql migration does not populate all _localization_links tables correctly

### ISSUE THREAD

**Issue by jodok** [strapi/migration-scripts#32]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Source Strapi version: 3.6.8
- Target Strapi version: 4.3.2
- Source Database: postgres 13
- Target Database: postgres 13
- Operating system: OSX
- Which script are you running: v3-sql-to-v4-sql

### Describe the bug

The `blog_post_categories_localizations_links` table of one of my content types is not being properly populated. Only the first column `blog_post_category_id` column populated but not the `inv_blog_post_category_id` column. However for some content types with similar complexity this works (i also have other content types that don't work either).

### Steps to reproduce the behavior

this is the v4 content type definition:

```
{
  "kind": "collectionType",
  "collectionName": "blog_post_categories",
  "info": {
    "singularName": "blog-post-category",
    "pluralName": "blog-post-categories",
    "displayName": "Blog Post Category",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "name": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string",
      "unique": true,
      "required": true
    }
  }
}
```

the v3 content type definition:

```
{
  "kind": "collectionType",
  "collectionName": "blog_post_categories",
  "info": {
    "name": "Blog Post Category",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "name": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string",
      "unique": true,
      "required": true
    }
  }
}
```

The v3 database shows the following records (interestingly the column is named `blog-post_id` and not as expected `related_blog_post_id`. maybe this is a no-issue, could be because of the `-` vs. `_`:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/158125/183265735-a2188735-5447-4425-aa0d-9e151f3adfb1.png">

The v4 database:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/158125/183265785-58291a3f-c5be-48e4-976c-5a1dde43276c.png">

### Expected behavior

i'd expect the v4 table to be properly populated. 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/158125/183265808-9658014f-d10b-4daf-a33b-89a724493bcc.png">

### Additional context

might be related to https://github.com/strapi/migration-scripts/issues/29

**Comment by derrickmehaffy** [comment]
Can't reproduce currently, here is a 7 minute video with me going through the process of migration for localization. If I missed anything please feel free to let me know.

https://www.loom.com/share/f7dbe172df154a5d8be22d466d6ccb8d

**Comment by jodok** [comment]
i created a quick video about the problem: https://youtu.be/NZTNWLcMwW8

(we've migrated our site successfully, but had to fix the localizations in the database manually)

**Comment by derrickmehaffy** [comment]
> i created a quick video about the problem: https://youtu.be/NZTNWLcMwW8
> 
> (we've migrated our site successfully, but had to fix the localizations in the database manually)

Can you make sure you have the latest version of the data migration script?

**Comment by jodok** [comment]
yes, latest checkout from main

**Comment by derrickmehaffy** [comment]
@jodok can you try to reproduce this in a fresh project as I still haven't been able to get to the same error as you.

**Comment by jodok** [comment]
i'm sorry, we manually migrated our project and fixed the missing links manually. feel free to close the issue if you don't want to further investigate. thanks for your support so far!

**Comment by derrickmehaffy** [comment]
Sounds fine, if someone else hits the issue we can reopen it but without reproduction steps (and we can't reproduce) then I'll set this as closed.

**Comment by pepijn-vanvlaanderen** [comment]
@derrickmehaffy we ran into the same issue. We have opened a PR with a small fix: https://github.com/strapi/migration-scripts/pull/50
