### ISSUE TITLE
(node:13348) UnhandledPromiseRejectionWarning: error: insert into "up_users"

### ISSUE THREAD

**Issue by kenanshrbage** [strapi/migration-scripts#34]
i have this problem by migrate from v3 to v4
can somebody help me to fix this problem or does somebody have any idea ?
thanks in advance

Migrating 25786 items from users-permissions_user to up_users
users-permissions_user batch #1
(node:13348) UnhandledPromiseRejectionWarning: error: insert into "up_users" ("academy_department", "address_city", "address_country", "address_street", "address_zip", "billing", "blocked", "cities", "comments", "confirmation_token", "confirmed", "created_at", "created_by_id", "customer_id", "customer_number", "deletion_at", "description", "email", "email_confirmed", "id", "industry", "international_area_code", "language", "name", "organization_size", "partner_academy", "password", "phone", "privacy_consent_at", "provider", "reset_password_token", "slug", "stripe_customer_id", "subscriptions", "terms_consent_at", "token_version", "type", "updated_at", "updated_by_id", "username", "website_url", "welcomed_at")

**Comment by derrickmehaffy** [comment]
Please follow the bug report template as it provides critical information we need to reproduce the bugs.

**Comment by kenanshrbage** [comment]
the problem actually because of custom extension, actually the columns with the relation wont be existing.
i dont know why ? so that, it is very kind from you when you could help me
