### ISSUE TITLE
Error inserting relation field to up_users

### ISSUE THREAD

**Issue by Barenstaden** [strapi/migration-scripts#38]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Source Strapi version: 3.6.8
- Target Strapi version: 4.3.4
- Source Database: Sqlite3
- Target Database: Sqlite3
- Operating system: MacOS
- Which script are you running: v3-sql-v4-sql

### Describe the bug

Relation fields on the user model fails to migrate to V4 as schema is not loaded in migrateUser.js.

### Steps to reproduce the behavior

1. Create relation field on user model in v3
2. Migrate strapi code from v3 to v4
3. Migrate sqlite3 db from v3 to v4
4. See error below

[Error: insert into `up_users` (all insert queries), SQLITE_ERROR: table up_users has no column named country] {
  errno: 1,
  code: 'SQLITE_ERROR'
}

### Expected behavior
The script should create relations on the user model in the same way as custom made models.

**Comment by derrickmehaffy** [comment]
Discussed this morning with @martincapek who has it on his todo ASAP once he gets a free slot. (thanks @martincapek :pray: )

**Comment by martincapek** [comment]
Hi @GregorSondermeier and @Barenstaden can you please test it? It should be fixed #72

**Comment by Barenstaden** [comment]
Hi @martincapek, thank you for the update! All relations are migrated properly now 🎉

**Comment by derrickmehaffy** [comment]
Thanks for this, I'll review the PR hopefully this week so we can get it merged!

**Comment by ADNANALK** [comment]
Hi @derrickmehaffy 
I have the same error 
- Create a relation field on user model in v3
- Migrate strapi code from v3 to v4
- Migrate MYSQL DB from v3 to v4
See error below


 code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'company' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "insert into `up_users` (`account_number`, `birth_date`, `blocked`, `change_password_date`, `company`, `confirmation_token`,
 `confirmed`, `country`, `created_at`, `created_by_id`, `description`, `email`, `email_confirmed`, `firebase_token`, `full_name`, `
gender`,


I already have too many relations in my user  model in v3,
So can you please give me an estimated time for fixing this issue? I will appreciate

**Comment by ADNANALK** [comment]
I checkout  to the git branch: [38-error-inserting-relation-field-to-up_users]

the "company" relation with "up_user" is fixed, but still I have a problem here with another relations,


invitee\schema.json:
"user": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::users-permissions.user",
      "inversedBy": "invitees"
    },
    
 company\schema.json:
 "users_permissions_users": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "plugin::users-permissions.user",
      "mappedBy": "company"
    },
    
    
    
User\schema.json:
"company": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::company.company",
      "inversedBy": "users_permissions_users"
    },
 "invitees": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::invitee.invitee",
      "mappedBy": "user"
    },
    
    
So  "company" relation "manyToOne"  I think is fixed, but  "invitees" relation "oneToMany" is not in  [38-error-inserting-relation-field-to-up_users] https://github.com/strapi/migration-scripts/pull/72 pull request
