### ISSUE TITLE
Double stringification of conditions column values on the admin_permissions table.

### ISSUE THREAD

**Issue by ConradP** [strapi/migration-scripts#39]
### Required System information

- Node.js version: 14.20.0
- NPM version: 6.14.17
- Source Strapi version: 3.6.8
- Target Strapi version: 4.3.6
- Source Database:  sqlite or mysql (verified on both)
- Target Database: sqlite or mysql (verified on both)
- Operating system:  Ubuntu 22.04 LTS
- Which script are you running: v3-sql-v4-sql

### Describe the bug
The conditions values in the admin_permissions tables are improperly formatted after running the migration script, this causes application crashes for admin users assigned to any role created pre-migration besides the super admin.

### Steps to reproduce the behavior
* create a quickstart v3 project 
* add an admin user to the project, assign them the editor or author role
* create a quickstart v4 project 
* migrate the database from v3 to v4 using the migration script configured for the sqlite databases
* start the v4 application
* log in to the dashboard as the created user
* dashboard will crash and 500 errors observed on the server side

### Expected behavior
The dashboard does not crash and the server does not error.

**Comment by ConradP** [comment]
I have created #40 to resolve this issue, it has been verified for both SQLite and MySQL/MariaDB databases. I have not tested it on a PostgreSQL database

**Comment by derrickmehaffy** [comment]
Reopening this as I had to revert the PR merge of #40 as other users were reporting problems in https://github.com/strapi/migration-scripts/issues/19
