### ISSUE TITLE
Mongo db is hardcoded to be `strapi`

### ISSUE THREAD

**Issue by laurenskling** [strapi/migration-scripts#43]
which in my case was the development database, and not `production` I was trying to connect to. Took my a while before i realized   what was happing 🥲 

https://github.com/strapi/migration-scripts/blob/25ab4e6c270554478c30a257baa5adfcbdc750e0/v3-mongodb-v3-sql/index.js#L96

**Comment by derrickmehaffy** [comment]
so sorry about that @laurenskling indeed :see_no_evil: this is what happens when I test using `strapi` as database names lol. Working on a fix now

**Comment by laurenskling** [comment]
Haha no worries mate. I'm very grateful for these migrations. Just wanted to help out the next developer :)
