### ISSUE TITLE
BUG: 1:1 Relation in Component does not get migrated, due to missing column in v4 table.

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/migration-scripts#5]
> v3-sql-v4-sql (pg 13 to pg13)
> 3.6.8 -> 4.1.9

# Issue

Thanks for the migration scripts. However when executing the migration, I get the error:
`Column »author« of relation »components_blog_blog_bases« does not exists.`.

In the mentioned v3 component we have a OneToOne relation to author like this (as described [here](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code/backend/content-type-schema.html#updating-content-type-relations) for content types):

```
"author": {
      "model": "author"
    }

We migrated code to v4 like this:
"author": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::author.author"
    }
```

Strapi creates the following tables in database (new table components_blog_blog_bases_categories_links on v4):

**DBv3:**
components_blog_blog_bases          
components_blog_blog_bases__categories  

**DBv4:**
components_blog_blog_bases                 
components_blog_blog_bases_author_links     
components_blog_blog_bases_categories_links 

Is it correct that strapi v4 creates the new table components_blog_blog_bases_categories_links for OneToOne relations?

**It looks like, that you implemented this for models but not for components?
Can you please provide a solution to migrate relations in components?**

## Setup

Simple Component with a 1:1 Relation.

### V3
![image](https://user-images.githubusercontent.com/5942270/166686465-138c20ad-d87c-4789-8349-71c327c2006b.png)

A 1:1 Relation gets added as a separate column with the id of the target.
![image](https://user-images.githubusercontent.com/5942270/166686719-a8648f7e-cc77-4db0-a822-84a51a2726cc.png)

A 1:Many Releation (here categories) is a separate table

![image](https://user-images.githubusercontent.com/5942270/166686786-807ac43f-4859-4a65-96dc-966fccbc7414.png)

### V4
![image](https://user-images.githubusercontent.com/5942270/166686488-6c09f96e-8ef0-47c6-a524-78ba48be9bea.png)

V4 creates separate tables for 1:1 and 1:Many Relations

![image](https://user-images.githubusercontent.com/5942270/166686856-adbc5759-bfe1-4724-96a1-068f45ea6af4.png)

The script is however still looking for the author column in the v4 table, which of course now does not exist.

## Tech

yarn 3.2.0
node 16.15.0
postgres 13

**Comment by skyclb** [comment]
I ran into the same error message when dealing with `oneToOne` and `oneToMany` relations in components. It seems, that the script does not take relations into account for components since it tries to insert into the v3 relation field in `components_<folder>_<component_name>` instead of in to new `components_<folder>_<component_name>_<relation_name>_links` table.

**Comment by jacargentina** [comment]
I'm. having a similar error, any advance on a fix ?

**Comment by paulpopus** [comment]
Unfortunately I don't have time to update and make a PR to the scripts right now but here's what worked for me in case someone's struck for time and needs a quick fix:

Create the missing columns in the new V4 database so that your components can migrate over safely, then you can manually export and re-import the data from your components__% table into the components_COMPONENT_FIELD_links tables using a tool like pgadmin

Note that this has been okay for my particular use case because the data we had to deal with was very limited.

**Comment by TomWebbio** [comment]
I'm having the exact same issues. Seeing as we have over a hundred relations, manually writing queries to add columns and then fix the data will be a lot of work. 

Is there any chance of this being fixed in the import tool?

**Comment by Meljesson** [comment]
Is the Strapi team working on this script? I'm having the same issues as the others here. I've written queries that added missing columns the strapi_permission to admin_permissions issue but seeing as I have lots of relations, that'll be a lot of work especially since my strapi instance gets used everyday

**Comment by LucaNerlich** [comment]
No communication at all, after initial "beta" script release.

**Comment by derrickmehaffy** [comment]
> Is the Strapi team working on this script? I'm having the same issues as the others here. I've written queries that added missing columns the strapi_permission to admin_permissions issue but seeing as I have lots of relations, that'll be a lot of work especially since my strapi instance gets used everyday

> No communication at all, after initial "beta" script release.

It's in our to-do, please keep in mind we have a lot of stuff going on and still a very small team. If you are interested in helping by providing pull requests like many others in our community please do. In the meantime if you are unable to assist us, please wait patiently and please remember to abide by our [Code of Conduct](https://forum.strapi.io/faq)

**Comment by LucaNerlich** [comment]
Thanks :)

Hope you can understand the frustration some parts of the community are feeling - v4 out for many months, but somewhat still stuck with that migration ahead of them.

**Comment by derrickmehaffy** [comment]
> Thanks :)
> 
> Hope you can understand the frustration some parts of the community are feeling - v4 out for many months, but somewhat still stuck with that migration ahead of them.

Trust me, it's not just the community that is frustrated but there is only so many working hours in a day and only so many of us that can actually do anything. There are far more community members than us which includes a lot of GitHub issues, Discord messages, Forum post/replies, Pull requests, twitter messages, emails, .... the list is long.

Benefit of open source is the source is there, those who have the technical skill to dive in are in the same boat as us.

**Comment by TomWebbio** [comment]
Thanks for the reaction, Derrick. Of course, I understand that you guys are really busy, and the scripts are still in beta after all. 

It would be very helpful to have some kind of timeline on when you are going to start working on this issue. It'd help me out immensely in terms of planning. :)

**Comment by mannp** [comment]
> Trust me, it's not just the community that is frustrated but there is only so many working hours in a day and only so many of us that can actually do anything.

It's disappointing, though, that such a good product does not have a designed data path to a major upgrade.

It appears that it is actually just not a priority.

**Comment by derrickmehaffy** [comment]
I shared more context in our [Discord](https://discord.strapi.io): 
![image](https://user-images.githubusercontent.com/8593673/169918052-35edaa76-a472-4980-ad7a-07153592f9a4.png)
