### ISSUE TITLE
Incorrect logic for getting id column of component field in relation link table

### ISSUE THREAD

**Issue by PritamSangani** [strapi/migration-scripts#60]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.7.0
- Source Strapi version: 3.6.8
- Target Strapi version: 4.3.8
- Source Database: mysql
- Target Database: mysql
- Operating system: OSX
- Which script are you running:  v3-sql-v4-sql

### Describe the bug

When migrating relations, when one side of the relationship is a component, the id column of the component field in the link table is incorrectly generated in some cases. This is causing the migration of some component relations to be skipped.

For my specific case, my component name is `teacher_notes` and the relation column name in the link table is `teacher_notes_id`. However, the migration scripts is trying to migrate to a column in the link table called `teacher_note_id` (which doesn't exist) so is skipped.

### Steps to reproduce the behavior

Hard to reproduce as it is project-specific.

### Expected behavior

The relation column name in the link table for a component should be in the format `{component_name}_id`.

### Code snippets

https://github.com/strapi/migration-scripts/blob/9ce036217a0bb8daef65523f1e5e6c56602b279a/v3-sql-v4-sql/migrate/helpers/relationHelpers.js#L70-L72

^ This is where the column name for a relation is being generated.

### Additional context

Within Strapi itself, the name of the relation column in a link table for a component is generated in the format: `{relation_model_name}_id`. However, in the migration scripts, for all cases, the column name for a relation in the link table is being formatted using the `pluralize` library, leading to column names for some component relations being incorrect.

**Comment by colearendt** [comment]
Not sure if this is related, but I'm getting an `id` related error in my migration from v3 to v4

```
Migrating 18/32 items from core_store to strapi_core_store_settings
(node:62909) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is undefined.
    at Object.migrateTables (/Users/colearendt/working/strapi-migration-scripts/v3-sql-v4-sql/migrate/migrateCoreStore.js:28:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async migrate (/Users/colearendt/working/strapi-migration-scripts/v3-sql-v4-sql/migrate/index.js:63:5)
    at async f (/Users/colearendt/working/strapi-migration-scripts/v3-sql-v4-sql/index.js:6:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:62909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:62909) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by XuluWarrior** [comment]
I hit this problem as well.  In my case I had a component named `activity_with_reps` with a one to one relationship to a collection named `activity`.
Strapi generates a table, `components_category_activities_with_reps_activity_links` with the fields
```
| id | activity_with_reps_id | activity_id |
```
The migration script expects the component id field to be `activity_with_rep_id`

I don't have any relationships which aren't between components and collections, so I don't know how other relationship tables are constructed.  But not singularizing the component entity name (as in #61) seems correct in that case.

**Comment by n-sikka** [comment]
@colearendt Could you please elaborate a bit on how you can stop the migration script from creating the v4 schema? I'm currently trying to migrate quite complex schemas and I've a bunch of relational fields and I can't find much in the documentation on what to do here. Any help would be super useful! 🙏

**Comment by colearendt** [comment]
@n-sikka Yes, apologies for not clarifying. The upgrade documentation is here:

- https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html
- https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data/sql.html#global-changes

Specifically, I was following the set of steps under `Migration` in the v3-sql to v4-sql README: 

https://github.com/strapi/migration-scripts/tree/main/v3-sql-v4-sql#migration

In step 2 - "Run Strapi v4 in `develop` mode with empty DB to generate the DB structure," it is basically saying "let strapi v4 create the DB structure." Then the migration script will move your data from the v3 database to the v4 database.

When I was hitting this issue, I was running the migration script first (before Strapi v4 in `develop` mode), so the migration script was trying to create the database structure - that created the failures I mentioned.
