### ISSUE TITLE
Components with the same name as collections

### ISSUE THREAD

**Issue by XuluWarrior** [strapi/migration-scripts#68]
### Required System information

- Target Strapi version: 4.4.3
- Which script are you running: v3-sql-v4-sql

### Describe the bug

Strapi allows components to have the same name as collections but the migration script doesn't allow for this and results in link tables with only the component id set, with `null` for the collection.

If a component has a one to one relationship with a collection with the same name, Strapi uses the field name inv_{collectionname}_id in the links table to distinguish the names.

e.g.
If there is a collection named `activity` and a component also named `activity`, Strapi will generate a table, `components_category_activities_activity_links` with the fields
```
| id | activity_id | inv_activity_id |
```

I have created a PR, #67, which supports migrating into this kind of table.  It's a bit of a letterbox fix but it works for my migration.

**Comment by laurenskling** [comment]
I've just hit the same thing.

My use case:

I've got a contentType `column` and a component called `column` that allows you to pick a relationship to a `column` model. which results in table:
`| id | column_id | inv_column_id`

`inv_column_id` does not get filled in the migration, while other components that have relationships to a model _not_ sharing the name (thus, not getting a `inv_` columnName) are migrated fine.

**Comment by GregorSondermeier** [comment]
Can confirm this issue

**Comment by GregorSondermeier** [comment]
I forked this repo into my company's bitbucket and wrote a custom migration for it. Here is some abbreviated example code in case anyone is interested.

First off, I moved executing the custom migrations to the very end, because in my case I had to fix this and some other migrations that were not done properly by the script out-of-the-box.

```javascript
// v3-sql-v4-sql/migrate/index.js

16 -  migrateCustom

74 +  await migrateCustom.migrateTables();
75 +  processedTables.push(...migrateCustom.processedTables);
```

```javascript
// v3-sql-v4-sql/customMigrations/03_migrate_components.js

const { migrateTable } = require('./utils/migrate-table');

// Tables that should not be proccessed later
const processedTables = [];


/**
 * @type {
 *   Array<{
 *     v3TableName: string;
 *     v4TableName: string;
 *     v3ToV4ColumnMappings: Record<string, string>
 *   }>
 * }
 */
const tablesToMigrate = [
  {
    v3TableName: 'csb_teaching_units',
    v4TableName: 'csb_teaching_units_teaching_unit_links',
    v3ToV4ColumnMappings: {
      id: 'teaching_unit_id',
      teachingUnit: 'inv_teaching_unit_id',
    },
  },
]

// Custom migration function, handles DB reads and writes
async function migrateTables() {
  for (const tableToMigrate of tablesToMigrate) {
    processedTables.push(await migrateTable(tableToMigrate));
  }
}

module.exports = {
  processedTables,
  migrateTables,
};
```

```javascript
// v3-sql-v4-sql/customMigrations/utils/migrate-table.js

const _keys = require('lodash/keys');
const _map = require('lodash/map');
const _mapKeys = require('lodash/mapKeys');
const { dbV3, dbV4 } = require('../../config/database');

/**
 * migrates table data from v3 table to v4 table.
 *
 * @param { Object } args
 * @param { string } args.v3TableName
 * @param { string } args.v4TableName
 * @param { Record<string, string> } args.v3ToV4ColumnMappings
 *
 * @return { Promise<string> } - The processed v3 table name
 */
async function migrateTable({
  v3TableName,
  v4TableName,
  v3ToV4ColumnMappings
}) {
  const v3Data = await dbV3(v3TableName).select(_keys(v3ToV4ColumnMappings));

  const v4Data = _map(v3Data, (rowV4) =>
    _mapKeys(rowV4, (value, key) =>
      v3ToV4ColumnMappings[key],
    ),
  );

  console.log(`Migrating ${v3Data.length} items from ${v3TableName} to ${v4TableName}`);
  await dbV4(v4TableName).truncate();
  await dbV4(v4TableName).insert(v4Data);

  return v3TableName;
}

module.exports = {
  migrateTable,
};
```
