### ISSUE TITLE
Localized entries are not migrated correctly - _localization_links tables missing values in inv_* fields

### ISSUE THREAD

**Issue by sarsonj** [strapi/migration-scripts#71]
### Required System information

- Node.js version: 14.2
- Source Strapi version: 3.6.10
- Target Strapi version: 4.5.1
- Source Database: mysql
- Target Database: mysql
- Operating system: Linux
- Which script are you running: v3-sql-v4-sql

### Describe the bug

I run data migration from 3.6.10 version to latest 4.5.1. The migration finished, but for localized entries no links were correctly created. The `_localization_links` tables are not empty, but the `_inv` field is always null. Like:

<img width="402" alt="Screenshot 2022-11-21 at 17 18 18" src="https://user-images.githubusercontent.com/925756/203105257-8ee71a12-ca90-49d8-b1eb-c7ac690f5774.png">

**Comment by sarsonj** [comment]
I made analyzation what is happening and the problem is, that in the original 3.x version table, the link to translated content field is named "blog-article_id". The migrateItem method in migrateFields.js converts this field to the same blog_article_id. I am not sure, when naming convention changes, looks like newer version are using related_ prefix.

Screenshot of 3.x table:

<img width="356" alt="Screenshot 2022-11-22 at 11 00 47" src="https://user-images.githubusercontent.com/925756/203285538-691dcbef-5be4-4b61-bc48-252005b5a5e9.png">

**Comment by martincapek** [comment]
Hi, this should be fixed in #73 and happens due to the Strapi update.

**Comment by derrickmehaffy** [comment]
fixed by: https://github.com/strapi/migration-scripts/pull/73
