### ISSUE TITLE
Tables with plural names from v3 not mapped to singular names in v4

### ISSUE THREAD

**Issue by paulpopus** [strapi/migration-scripts#9]
> v3-sql-v4-sql (pg 10 to pg13)
> 3.6.8 -> 4.1.9

### Describe the bug

All table names for content types in v3 use a plural name, but in v4 some of them use a singular name instead.

Error:
```
DESTINATION TABLE countries DOES NOT EXISTS
DESTINATION TABLE timezones DOES NOT EXISTS
```

In v4 the tables for these are country and timezone respectively.

### Steps to reproduce the behavior

Migrate a content type with a plural name such as "countries" from v3 to a singular name in v4 "country".

### Expected behavior / solution

Ability to map previous table names to new ones in config?

I'm not sure what the ideal solution is right now, I'm going to try and fix it in my script and I'll update this issue if I've made any progress.

**Comment by LucaNerlich** [comment]
I think the origin of this issue is, when the v3 table / content type has been created with a plural key/name.

For example V3 Content Type: BlogPosts instead of BlogPost. This will create a schema thats not conform with v4, since the key is already plural (v4 now has separate singular and plural names), therefore the script breaks / v4 startup fails.

**Comment by paulpopus** [comment]
Here's my quick solution....

In `helpers` I've added a new file `mapPluralTables.js` with
```js
const tableMapping = {
  countries: 'country',
}

function mapPluralTables(table) {
  if (tableMapping[table]) {
    return tableMapping[table]
  } else return table
}

module.exports = {
  mapPluralTables,
}
```

Then in the `migrate/index.js` require the new helper function at the top
```js
const { mapPluralTables } = require('./helpers/mapPluralTables')
```

I've extended the table name return for my database `row => row.table_name` like this:

```js
if (isPGSQL) {
  tables = (
    await dbV3("information_schema.tables")
      .select("table_name")
      .where("table_schema", "public")
  ).map((row) => mapPluralTables(row.table_name));
}
```


If I have some time after I finish this migration I may open up a PR if this sounds like a decent solution for others.

**Comment by derrickmehaffy** [comment]
Hello I'm unable to reproduce this given the current state of the migration script. Could you test this again and see if you still hit the same issue?

**Comment by derrickmehaffy** [comment]
No for now I think that's fine. I'll set it as closed and if someone else hits the issue again and provide reproduction steps they can respond and we can reopen.

Thanks!
